datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:  
      - name: Loki
        type: loki
        access: proxy
        url: "http://loki-gateway:80"
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "http://prometheus-server"
