extraScrapeConfigs: |
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'promtail'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        regex: promtail
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 3101
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
