# default values at: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml

primary:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3
      memory: 8Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
