apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deployment.yaml

patches:
  - path: patches/patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: busybox
      labelSelector: app=busybox
