apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-playwright-service
  labels:
    app: {{ .Release.Name }}-playwright-service
spec:
  selector:
    app: {{ .Release.Name }}-playwright-service
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP