repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: open-webui
    url: https://helm.openwebui.com/
  - name: minio
    url: https://charts.min.io/
  - name: langflow
    url: https://langflow-ai.github.io/langflow-helm-charts

releases:
# --- monitoring ---
  - name: loki
    # https://github.com/grafana/loki/tree/main/production/helm/loki
    chart: grafana/loki
    namespace: monitoring
    version: 6.27.0
    values:
      - loki_values.yaml
  - name: prom-stack
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 69.4.1
    values:
      - prometheus_values.yaml
    needs:
      - monitoring/loki
  - name: promtail
    # https://github.com/grafana/helm-charts/tree/main/charts/promtail
    chart: grafana/promtail
    namespace: monitoring
    version: 6.16.6
    values:
      - promtail_values.yaml
    needs:
      - monitoring/loki

# --- storage ---
  - name: postgres
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    namespace: postgres
    version: 16.4.9
    values:
      - postgres_values.yaml
    needs:
      - monitoring/loki
      - monitoring/promtail
      - monitoring/prom-stack
  - name: minio
    chart: minio/minio
    namespace: minio
    version: 5.4.0
    values:
      - minio_values.yaml
    needs:
      - monitoring/loki
      - monitoring/promtail
      - monitoring/prom-stack

# --- apps ---
  - name: open-webui
    chart: open-webui/open-webui
    namespace: open-webui
    version: 6.4.0
    values:
      - open-webui_values.yaml
    needs:
      - monitoring/loki
      - monitoring/promtail
      - monitoring/prom-stack
  - name: langflow-ide
    chart: langflow/langflow-ide
    namespace: langflow
    version: 0.1.1
    values:
      - langflow-ide_values.yaml
    needs:
      - monitoring/promtail
      - monitoring/prom-stack
  - name: langflow-runtime
    chart: langflow/langflow-runtime
    namespace: langflow
    version: 0.1.1
    values:
      - langflow-runtime_values.yaml
    needs:
      - monitoring/promtail
      - monitoring/prom-stack
      - langflow-ide
  - name: litellm
    chart: oci://ghcr.io/berriai/litellm-helm
    namespace: litellm
    version: 0.1.670
    values:
      - litellm_values.yaml
    needs:
      - monitoring/prom-stack
      - monitoring/promtail