livenessProbe:
  httpGet:
    path: /api/v1/version
    port: http
  initialDelaySeconds: 30
readinessProbe:
  httpGet:
    path: /api/v1/version
    port: http
  initialDelaySeconds: 30

ingress:
  enabled: true
  className: nginx
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: langflow-runtime.server02.creutz.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: tls-server02-creutz-io
      hosts:
        - "*.server02.creutz.io"