ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: litellm.server02.creutz.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-server02-creutz-io
      hosts:
        - "*.server02.creutz.io"