ingressClass:
  name: traefikkkk

# providers:
#   kubernetesCRD:
#     ingressClass: traefik
#   kubernetesIngress:
#     ingressClass: traefik

deployment:
  dnsPolicy: ClusterFirstWithHostNet

service:
  type: ClusterIP
  spec:
    # externalTrafficPolicy: Local
  externalIPs:
    - 192.168.0.10 # dirty but necessary for hostnetwork mode with traefik

hostNetwork: true

ports:
  metrics:
    port: 9101
# metrics:
#   prometheus:
#     service:
#       enabled: true
#     disableAPICheck: false
#     serviceMonitor:
#       enabled: true
#       metricRelabelings:
#         - sourceLabels: [__name__]
#           separator: ;
#           regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
#           replacement: $1
#           action: drop
#       relabelings:
#         - sourceLabels: [__meta_kubernetes_pod_node_name]
#           separator: ;
#           regex: ^(.*)$
#           targetLabel: nodename
#           replacement: $1
#           action: replace
#       jobLabel: traefik
#       interval: 30s
#       honorLabels: true
#     prometheusRule:
#       enabled: true
#       rules:
#         - alert: TraefikDown
#           expr: up{job="traefik"} == 0
#           for: 5m
#           labels:
#             context: traefik
#             severity: warning
#           annotations:
#             summary: "Traefik Down"
#             description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
