apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-<share-name>
spec:
  capacity:
    storage: 1Gi # placeholder, will not be used
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-<namespace>-<share-name> # must match the one in the pvc
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: <ip-or-url>/<subdirs>/<share-name>##
    volumeAttributes:
      source: "//<ip-or-url>/<subdirs>/<share-name>"
    nodeStageSecretRef:
      name: <secret-name>
      namespace: <secret-namespace>
