apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deployment.yaml
  - base/service.yaml
  - base/configmap.yaml

namespace: kluctl
# patches:
#   - path: patches/increase-replicas.yaml
#   - path: patches/add-config-volume.yaml

# patchesJson6902:
#   - target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: app-one
#     path: patches/json-patch.yaml
