resources:
  # - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.3/components.yaml
  - upstream_manifests/namespace.yaml
  - upstream_manifests/app-1.yaml
  - upstream_manifests/app-2.yaml

patches:
  # Metrcis server
  # - patch: |-
  #     - op: add
  #       path: /spec/template/spec/containers/0/args/-
  #       value:
  #         --kubelet-insecure-tls
  #     - op: add
  #       path: /metadata/namespace
  #       value: kube-system
  #   target:
  #     version: v1
  #     kind: Deployment
  #     name: metrics-server
  #     namespace: kube-system
  # App-1
  - path: patches_rendered/app-1_patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app-1
  # App-2
  - path: patches_rendered/app-2_patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app-2


