apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-server02-creutz-io
spec:
  secretName: tls-server02-creutz-io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.server02.creutz.io"
