apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app2-monitor
  namespace: monitoring
  labels:
    app: app2
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app2
  endpoints:
    - port: metrics
      interval: 15s
      path: /actuator/prometheus
