apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app1-monitor
  namespace: monitoring
  labels:
    app: app1
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app1
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
