ARG SAMBA_VERSION=4.16.8

FROM alpine:3.17

ARG SAMBA_VERSION
# ARG SAMBA_RELEASE

RUN apk --update --no-cache add \
    bash \
    coreutils \
    jq \
    samba=${SAMBA_VERSION}-r0 \
    shadow \
    tzdata \
    yq \
  && rm -rf /tmp/*

COPY testfile.txt /shared_directory/subdirectory/testfile.txt
COPY entrypoint.sh /entrypoint.sh

EXPOSE 445

# VOLUME [ "/data" ]

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "smbd", "-F", "--debug-stdout", "--no-process-group" ]

HEALTHCHECK --interval=30s --timeout=10s \
  CMD smbclient -L \\localhost -U % -m SMB3