# default values: https://github.com/minio/minio/blob/master/helm/minio/values.yaml

mode: standalone

replicas: 1

persistence:
  size: 100Gi

resources:
  requests:
    memory: 1Gi

rootUser: "root"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m" # for large file uploads
  path: /
  hosts:
    - minio-api.server02.creutz.io
  tls:
    - hosts:
        - "*.server02.creutz.io"
      secretName: tls-server02-creutz-io

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  path: /
  hosts:
    - minio.server02.creutz.io
  tls:
    - hosts:
        - "*.server02.creutz.io"
      secretName: tls-server02-creutz-io

metrics:
  serviceMonitor:
    enabled: true
