apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: ytt-kapp
  labels:
    app: app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1-container
        image: nginx:latest
        ports:
        - containerPort: 80