# repositories:
#   - name: prometheus-community
#     url: https://prometheus-community.github.io/helm-charts
#   - name: grafana
#     url: https://grafana.github.io/helm-charts
#   - name: longhorn
#     url: https://charts.longhorn.io
#   - name: bitnami
#     url: https://charts.bitnami.com/bitnami

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.1
    values:
      - longhorn_values.yaml
    wait: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "/bin/sh"
        args:
          - -c
          - |
            COMPONENTS=(
              "deployment/csi-snapshotter"
              "deployment/csi-resizer"
              "deployment/csi-provisioner"
              "deployment/csi-attacher"
            )
            until kubectl get ${COMPONENTS[@]} -n longhorn-system; do 
              sleep 5
            done \
            && kubectl wait \
              --for=condition=Available ${COMPONENTS[@]} \
              -n longhorn-system \
              --timeout=300s \
            && sleep 5
    # deleting needs: kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag

  - name: prom-stack
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 67.5.0
    values:
      - prometheus_values.yaml
    needs:
      - longhorn-system/longhorn

  - name: loki
    # https://github.com/grafana/loki/tree/main/production/helm/loki
    namespace: monitoring
    chart: grafana/loki
    version: 6.24.0
    values:
      - loki_values.yaml
    needs:
      - longhorn-system/longhorn
      - monitoring/promtail

  - name: promtail
    # https://github.com/grafana/helm-charts/tree/main/charts/promtail
    namespace: monitoring
    chart: grafana/promtail
    version: 6.16.6
    values:
      - promtail_values.yaml
    needs:
      - longhorn-system/longhorn

  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql
    version: 16.3.4
    values:
      - postgres_values.yaml
    needs:
      - longhorn-system/longhorn
