csi:
  kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet" # use this for microk8s

persistence:
  defaultDataLocality: best-effort

defaultSettings:
  defaultDataPath: "/longhorn" # use this for microk8s
  defaultDataLocality: best-effort

ingress:
  enabled: false

metrics:
  serviceMonitor:
    enabled: true

longhornUI:
  replicas: 1