global:
  defaultStorageClass: longhorn-single-replica

architecture: replication

primary:
  persistence:
    size: 2Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: postgres
              app.kubernetes.io/name: postgresql
          topologyKey: kubernetes.io/hostname

readReplicas:
  replicaCount: 1
  persistence:
    size: 2Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: postgres
              app.kubernetes.io/name: postgresql
          topologyKey: kubernetes.io/hostname

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
