primary:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3
      memory: 8Gi
  persistence:
    size: 2Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
